<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZeG346V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZeG346V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZeG346V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZeG346V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZeG346V\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZeG346V',
    'container.build_id' => '736bc18c',
    'container.build_time' => 1666352951,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZeG346V');
